apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: infrastructure-postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgdata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infrastructure-postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
